-- Create a database of school containing the following tables
-- Students
-- Employees

-- Create a database of school containing the following tables
-- Account Holder
-- Staff
-- Devices



show databases;
CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE STUDENT(
STUDENT_ROLLNO INT,
STUDENT_NAME VARCHAR(20),
STUDENT_LASTNAME VARCHAR(20),
STANDARD INT,
STUDENT_CONTACT_NO INT);
INSERT INTO STUDENT VALUES(101,"SARANG","SARJEKAR",1,857496874);
INSERT INTO STUDENT(STUDENT_ROLLNO,STUDENT_NAME,STUDENT_LASTNAME,STANDARD,STUDENT_CONTACT_NO) VALUES
(102,"ANAND","BAJPAI",1,547896547),
(103,"ROHAN","GAIKWAD",1,587412369),
(104,"SANKET","SARJEK",1,587458962);
SELECT * FROM STUDENT;

SHOW DATABASES;

USE SCHOOL;
CREATE TABLE EMPLOYEES(
EMP_ID INT,
EMP_FULLNAME VARCHAR(30),
EMP_POSITION VARCHAR(20),
EMP_SALARY INT);
INSERT INTO EMPLOYEES(EMP_ID,EMP_FULLNAME,EMP_POSITION,EMP_SALARY)VALUES
(001,"JITENDRA KUMAR","PROFESSOR",15000),
(002,"RAJAN VARMA","SENIOR CLEARK",14000);
INSERT INTO EMPLOYEES(EMP_ID,EMP_FULLNAME,EMP_POSITION,EMP_SALARY)VALUES
(003,"NITIN MAHAJAN","HOD",20000),
(004,"SAFAR KHAN","CLERK",14000);

SELECT * FROM EMPLOYEES;
SELECT * FROM STUDENT;
SELECT * FROM STUDENT;
SELECT * FROM EMPLOYEES;
USE SCHOOL;
CREATE TABLE ACCOUNT_HOLDERS(
ACCOUNT_NAME VARCHAR(20),
ACCOUNT_NUMBER INT,
BRANCH VARCHAR(20));

INSERT INTO ACCOUNT_HOLDERS(ACCOUNT_NAME,ACCOUNT_NUMBER,BRANCH)VALUES
("NITIN MAHAJAN",12345,"STATE BANK"),
("SAFAR KHAN",12346,"AXIS BANK");

SELECT * FROM ACCOUNT_HOLDERS;

USE SCHOOL;
CREATE TABLE STAFF(
EMP_ID INT,
EMP_NAME VARCHAR(20));

INSERT INTO STAFF VALUES(10001,"YOGESH WAGH");
INSERT INTO STAFF VALUES(10002,"RAJESH PATIL");
SELECT * FROM STAFF;
USE SCHOOL;
CREATE TABLE DEVICES(
DEVICE_NAME varchar(20),
DEVICE_MODEL_YR INT);
INSERT INTO DEVICES VALUES("MOBILE",2002);
SELECT * FROM DEVICES;
